// <auto-generated />
using System;
using CityGasWebApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace CityGasWebApi.Migrations
{
    [DbContext(typeof(CityGasContext))]
    [Migration("20201023091620_workticket")]
    partial class workticket
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("CityGasWebApi.Models.Archives.Device", b =>
                {
                    b.Property<Guid>("GId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Ability")
                        .HasColumnType("text");

                    b.Property<DateTime>("AcceptDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("ArrivalDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("AssetNo")
                        .HasColumnType("text");

                    b.Property<string>("BuyContractNo")
                        .HasColumnType("text");

                    b.Property<DateTime>("BuyDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Company")
                        .HasColumnType("text");

                    b.Property<double>("Cost")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreateUser")
                        .HasColumnType("text");

                    b.Property<DateTime>("DebugFinishDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Depreciation")
                        .HasColumnType("text");

                    b.Property<string>("DeviceName")
                        .HasColumnType("text");

                    b.Property<string>("DeviceType")
                        .HasColumnType("text");

                    b.Property<string>("DeviceType1")
                        .HasColumnType("text");

                    b.Property<string>("FacPhone")
                        .HasColumnType("text");

                    b.Property<string>("Factory")
                        .HasColumnType("text");

                    b.Property<DateTime>("FactoryDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("FactoryNo")
                        .HasColumnType("text");

                    b.Property<string>("Formalities")
                        .HasColumnType("text");

                    b.Property<string>("Function")
                        .HasColumnType("text");

                    b.Property<string>("HolderSituation")
                        .HasColumnType("text");

                    b.Property<double>("InspectCycle")
                        .HasColumnType("double precision");

                    b.Property<string>("InstallAddress")
                        .HasColumnType("text");

                    b.Property<string>("IsKeyPart")
                        .HasColumnType("text");

                    b.Property<string>("IsSpecial")
                        .HasColumnType("text");

                    b.Property<DateTime>("LastUpdateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("LastUpdateUser")
                        .HasColumnType("text");

                    b.Property<string>("LicensesCompany")
                        .HasColumnType("text");

                    b.Property<string>("OtherParams")
                        .HasColumnType("text");

                    b.Property<string>("PressType")
                        .HasColumnType("text");

                    b.Property<double>("QualityYears")
                        .HasColumnType("double precision");

                    b.Property<string>("Remark")
                        .HasColumnType("text");

                    b.Property<string>("ResponseUser")
                        .HasColumnType("text");

                    b.Property<string>("Size")
                        .HasColumnType("text");

                    b.Property<string>("Source")
                        .HasColumnType("text");

                    b.Property<string>("Spec")
                        .HasColumnType("text");

                    b.Property<string>("State")
                        .HasColumnType("text");

                    b.Property<string>("Unit")
                        .HasColumnType("text");

                    b.Property<DateTime>("UseDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UsePart")
                        .HasColumnType("text");

                    b.Property<string>("UseRegistNo")
                        .HasColumnType("text");

                    b.Property<double>("Weight")
                        .HasColumnType("double precision");

                    b.HasKey("GId");

                    b.ToTable("Device");
                });

            modelBuilder.Entity("CityGasWebApi.Models.BaseInfo.Driver", b =>
                {
                    b.Property<Guid>("PK")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Company")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreateUser")
                        .HasColumnType("text");

                    b.Property<DateTime>("LastUpdateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("LastUpdateUser")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Remark")
                        .HasColumnType("text");

                    b.HasKey("PK");

                    b.ToTable("Driver");
                });

            modelBuilder.Entity("CityGasWebApi.Models.BaseInfo.OilStation", b =>
                {
                    b.Property<Guid>("PK")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Branch")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreateUser")
                        .HasColumnType("text");

                    b.Property<string>("District")
                        .HasColumnType("text");

                    b.Property<string>("HMIIP")
                        .HasColumnType("text");

                    b.Property<DateTime>("LastUpdateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("LastUpdateUser")
                        .HasColumnType("text");

                    b.Property<string>("Latitude")
                        .HasColumnType("text");

                    b.Property<float>("LevelCalcFactor")
                        .HasColumnType("real");

                    b.Property<float>("LevelCalcOffset")
                        .HasColumnType("real");

                    b.Property<string>("Longitude")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("PLCIP")
                        .HasColumnType("text");

                    b.Property<float>("PumpCalcFactor")
                        .HasColumnType("real");

                    b.Property<float>("PumpCalcOffset")
                        .HasColumnType("real");

                    b.Property<float>("PumpRatedFlow")
                        .HasColumnType("real");

                    b.Property<string>("Remark")
                        .HasColumnType("text");

                    b.Property<float>("VolumnPer1cm")
                        .HasColumnType("real");

                    b.HasKey("PK");

                    b.ToTable("OilStation");
                });

            modelBuilder.Entity("CityGasWebApi.Models.BaseInfo.Truck", b =>
                {
                    b.Property<Guid>("PK")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Company")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreateUser")
                        .HasColumnType("text");

                    b.Property<DateTime>("LastUpdateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("LastUpdateUser")
                        .HasColumnType("text");

                    b.Property<string>("LeadSealNumber")
                        .HasColumnType("text");

                    b.Property<string>("Number")
                        .HasColumnType("text");

                    b.Property<string>("Remark")
                        .HasColumnType("text");

                    b.Property<float>("Volumn")
                        .HasColumnType("real");

                    b.HasKey("PK");

                    b.ToTable("Truck");
                });

            modelBuilder.Entity("CityGasWebApi.Models.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Avatar")
                        .HasColumnType("text");

                    b.Property<string>("Branch")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreateUser")
                        .HasColumnType("text");

                    b.Property<string>("CurrentAuthority")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<DateTime>("LastUpdateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("LastUpdateUser")
                        .HasColumnType("text");

                    b.Property<string>("Mobile")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.Property<string>("Remark")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("CityGasWebApi.Models.Work.WorkTicket", b =>
                {
                    b.Property<Guid>("PK")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CarNumber")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreateUser")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Driver")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastUpdateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("LastUpdateUser")
                        .HasColumnType("text");

                    b.Property<float>("LevelAfterLoad")
                        .HasColumnType("real");

                    b.Property<float>("LevelBeginLoad")
                        .HasColumnType("real");

                    b.Property<string>("LoadStation")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LoadingActualBeginTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("LoadingActualEndTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("LoadingBeginTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("LoadingEndTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<float>("OilError")
                        .HasColumnType("real");

                    b.Property<float>("OilLoaded")
                        .HasColumnType("real");

                    b.Property<string>("OilLoader")
                        .HasColumnType("text");

                    b.Property<float>("OilUnloaded")
                        .HasColumnType("real");

                    b.Property<string>("OilUnloader")
                        .HasColumnType("text");

                    b.Property<string>("Remark")
                        .HasColumnType("text");

                    b.Property<string>("Reviewer")
                        .HasColumnType("text");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.Property<string>("SubSerialNumber")
                        .HasColumnType("text");

                    b.Property<float>("TaskDuration")
                        .HasColumnType("real");

                    b.Property<string>("UnloadStation")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UnloadingBeginTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("UnloadingEndTime")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("PK");

                    b.ToTable("WorkTicket");
                });
#pragma warning restore 612, 618
        }
    }
}
