// <auto-generated />
using System;
using CityGasWebApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace CityGasWebApi.Migrations
{
    [DbContext(typeof(CityGasContext))]
    [Migration("20201021081132_addfield_user")]
    partial class addfield_user
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("CityGasWebApi.Models.Archives.Device", b =>
                {
                    b.Property<Guid>("GId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Ability")
                        .HasColumnType("text");

                    b.Property<DateTime>("AcceptDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("ArrivalDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("AssetNo")
                        .HasColumnType("text");

                    b.Property<string>("BuyContractNo")
                        .HasColumnType("text");

                    b.Property<DateTime>("BuyDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Company")
                        .HasColumnType("text");

                    b.Property<double>("Cost")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreateUser")
                        .HasColumnType("text");

                    b.Property<DateTime>("DebugFinishDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Depreciation")
                        .HasColumnType("text");

                    b.Property<string>("DeviceName")
                        .HasColumnType("text");

                    b.Property<string>("DeviceType")
                        .HasColumnType("text");

                    b.Property<string>("DeviceType1")
                        .HasColumnType("text");

                    b.Property<string>("FacPhone")
                        .HasColumnType("text");

                    b.Property<string>("Factory")
                        .HasColumnType("text");

                    b.Property<DateTime>("FactoryDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("FactoryNo")
                        .HasColumnType("text");

                    b.Property<string>("Formalities")
                        .HasColumnType("text");

                    b.Property<string>("Function")
                        .HasColumnType("text");

                    b.Property<string>("HolderSituation")
                        .HasColumnType("text");

                    b.Property<double>("InspectCycle")
                        .HasColumnType("double precision");

                    b.Property<string>("InstallAddress")
                        .HasColumnType("text");

                    b.Property<string>("IsKeyPart")
                        .HasColumnType("text");

                    b.Property<string>("IsSpecial")
                        .HasColumnType("text");

                    b.Property<DateTime>("LastUpdateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("LastUpdateUser")
                        .HasColumnType("text");

                    b.Property<string>("LicensesCompany")
                        .HasColumnType("text");

                    b.Property<string>("OtherParams")
                        .HasColumnType("text");

                    b.Property<string>("PressType")
                        .HasColumnType("text");

                    b.Property<double>("QualityYears")
                        .HasColumnType("double precision");

                    b.Property<string>("Remark")
                        .HasColumnType("text");

                    b.Property<string>("ResponseUser")
                        .HasColumnType("text");

                    b.Property<string>("Size")
                        .HasColumnType("text");

                    b.Property<string>("Source")
                        .HasColumnType("text");

                    b.Property<string>("Spec")
                        .HasColumnType("text");

                    b.Property<string>("State")
                        .HasColumnType("text");

                    b.Property<string>("Unit")
                        .HasColumnType("text");

                    b.Property<DateTime>("UseDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UsePart")
                        .HasColumnType("text");

                    b.Property<string>("UseRegistNo")
                        .HasColumnType("text");

                    b.Property<double>("Weight")
                        .HasColumnType("double precision");

                    b.HasKey("GId");

                    b.ToTable("Device");
                });

            modelBuilder.Entity("CityGasWebApi.Models.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Avatar")
                        .HasColumnType("text");

                    b.Property<string>("Branch")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreateUser")
                        .HasColumnType("text");

                    b.Property<string>("CurrentAuthority")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<DateTime>("LastUpdateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("LastUpdateUser")
                        .HasColumnType("text");

                    b.Property<string>("Mobile")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.Property<string>("Remark")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.ToTable("User");
                });
#pragma warning restore 612, 618
        }
    }
}
